### ISSUE TITLE
Binding gridData and gridConfig to the html?

### ISSUE THREAD

**Issue by BrianARice** [beiduo/ng-datatable#1]
In your example you show the js code... but how do bind gridData and gridConfig to the html?

Is there a non-minimized version of the code available?

**Comment by beiduo** [comment]
```
<ng-datatable config="$ctrl.gridConfig" receive="$ctrl.gridData" app-scope="$ctrl"></ng-datatable>
```

you can find the non-minimized js source code in the **/src** directory
